name = "Travelify"
license = "MIT"
description = "Lovely wordpress theme, now coming to Hugo. "
tags = ["syntax highlighting", "rss", "widgets", "google analytics", "responsive", "carousel", "slider"]
features = ["syntax highlighting", "rss", "widgets", "google analytics", "carousel", "responsive", "slider"]
min_version = 0.15
