#baseURL = "http://localhost:8888/public"
baseURL = "http://localhost:1313/miawebsite/public"
title = "Laboratoire Mathématiques, Image et Applications"
subtitle = "MIA Website"
languageCode = "en-us"
# preservetaxonomynames = true
theme = "ananke"
GoogleAnalytics = "" # Add your own Google analytics code here in the format UA-XXXXXXXX-X
canonifyURLs = true
# rssURI = "feed/" #deprecated feature

[params]
    # Tell me who you are
    author = "MIA"
    site_description = "Bienvenue sur le site du laboratoire MIA"
    copyright  = "Copyright"
     logo = "logolab.png"

    title_in_logo = true # set to true if you want the title along with the logo
    disable_mathjax = true # set to true to disable MathJax

    # Format dates with Go's time formatting
    date_format = "02 January, 2006"

    # Add custom assets with their paths relative to the static folder
    custom_css = []
    custom_js  = []



# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.


[[menu.main]]
    name  = "Le MIA"
    url   = "/about/"
    weight = 5

[[menu.main]]
        name  = "Présentation"
        url   = "/about/"
        parent = "Le MIA"
        weight = 7

[[menu.main]]
        name  = "Membres"
        url   = "/Membres/"
        parent = "Le MIA"
        weight = 7


[[menu.main]]
    name  = "Production"
    url   = "/production/"
    weight = 7

[[menu.main]]
    name  = "Publications"
    url   = "/publications/"
    parent = "Production"

[[menu.main]]
    name  = "Pré-publis"
    url   = "/publis/"
    parent = "Production"
    weight = 20

[[menu.main]]
    name  = "Démos"
    url   = "/demos/"
    parent = "Production"
    weight = 10

[[menu.main]]
    name  = "Seminaires"
    url   = "/seminaires/"
    parent = "Production"

[[menu.main]]
        name  = "Partenariats"
        url   = "/partenariats/"
        weight = 8

[[menu.main]]
        name  = "Infos Pratiques"
        url   = "/contact/"
        weight = 10


        [[menu.main]]
                name  = "Connexion à l'espace privé"
                url   = "/connexion/connexion/"
                weight = 11



              [[menu.main]]
                        name  = "Modèles et logo MIA"
                        url   = "/modeles/"
                        parent = "Connexion à l'espace privé"

                [[menu.main]]
                                name  = "Gestions des publications"
                                url   = "/publications/"
                                parent = "Connexion à l'espace privé"


                [[menu.main]]
                                name  = "Secrétariat"
                                url   = "/secretariats/"
                                parent = "Connexion à l'espace privé"

                [[menu.main]]
                                name  = "Bibliothèque-Base de données"
                                url   = "/biblio/"
                                parent = "Connexion à l'espace privé"

                [[menu.main]]
                                name  = "Ressources informatiques"
                                url   = "/ressources/"
                                parent = "Connexion à l'espace privé"

                [[menu.main]]
                                name  = "Gestion du site du MIA"
                                url   = "/gestion_site/"
                                parent = "Connexion à l'espace privé"

[social]
logo = "logouniv.png"
logorepub = "republique.png"
    github          = "example"
facebook        = "example"


# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
    archives = false # This feature is yet to be implemented because of limitations in Hugo's way of working.
    search = true
    mailchimp = true
    mailchimpform = true
    author = true

[params.slider]
    enable = true
    manual = false # Setting manual to true renders the slide selection to only those where the post has a slider=true option enabled
    num_features = 6 # The slider picks up the banner images from the N most recent posts, where num_features is N.
